import Link from 'next/link';
import { getAppointments } from '@/lib/data';

export default async function Appointments({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  const [{ view }, appts] = await Promise.all([searchParams, getAppointments()]);
  const calendar = view === 'calendar';
  return <main className="mx-auto max-w-7xl px-6 py-10"><Link href="/admin" className="text-brand">← Dashboard</Link><div className="mt-4 flex flex-wrap items-center justify-between gap-4"><h1 className="text-4xl font-black">Appointments</h1><div className="flex gap-2"><Link className={!calendar ? 'btn-primary' : 'btn-secondary'} href="/admin/appointments">List</Link><Link className={calendar ? 'btn-primary' : 'btn-secondary'} href="/admin/appointments?view=calendar">Calendar</Link></div></div>{calendar ? <div className="mt-8 grid gap-4 md:grid-cols-3">{appts.map((a:any)=><AppointmentCard key={a.id} a={a} compact />)}</div> : <div className="mt-8 grid gap-4">{appts.map((a:any)=><AppointmentCard key={a.id} a={a} />)}</div>}</main>;
}
function AppointmentCard({ a, compact=false }: { a:any; compact?: boolean }) { const lead=a.lead||{}; return <div className="card"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-black">{lead.name || a.leadName}</h2><p className="text-slate-600">{lead.projectType || a.projectType} · ZIP {lead.zipCode || a.zipCode}</p><p className="font-semibold">{new Date(a.scheduledAt).toLocaleString()} · {a.timezone || 'UTC'}</p><p className="text-sm text-slate-600">Contractor: {a.contractor?.companyName || lead.assignedContractor || 'Unassigned'} · Status: {a.status}</p>{!compact && <div className="mt-2 flex flex-wrap gap-3 text-sm">{a.rescheduleUrl && <a className="text-brand" href={a.rescheduleUrl}>Reschedule</a>}{a.cancellationUrl && <a className="text-red-600" href={a.cancellationUrl}>Cancel link</a>}</div>}</div><form action="/api/appointments" method="post" className="flex flex-wrap gap-2"><input type="hidden" name="id" value={a.id}/>{['Showed','NoShow','Won','Lost','Cancelled'].map(s=><button className="btn-secondary" name="status" value={s} key={s}>{s}</button>)}</form></div></div> }
